version: "3.5"
services:
  postgresql:
    container_name: klogga-timescale
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: timescale/timescaledb:latest-pg13
    ports:
      - "5432:5432"
