// Code generated by MockGen. DO NOT EDIT.
// Source: influx_exporter.go

// Package influx_exporter is a generated GoMock package.
package influxdb18

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "github.com/influxdata/influxdb1-client"
)

// MockInfluxClient is a mock of InfluxClient interface.
type MockInfluxClient struct {
	ctrl     *gomock.Controller
	recorder *MockInfluxClientMockRecorder
}

// MockInfluxClientMockRecorder is the mock recorder for MockInfluxClient.
type MockInfluxClientMockRecorder struct {
	mock *MockInfluxClient
}

// NewMockInfluxClient creates a new mock instance.
func NewMockInfluxClient(ctrl *gomock.Controller) *MockInfluxClient {
	mock := &MockInfluxClient{ctrl: ctrl}
	mock.recorder = &MockInfluxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfluxClient) EXPECT() *MockInfluxClientMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockInfluxClient) Write(bp client.BatchPoints) (*client.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", bp)
	ret0, _ := ret[0].(*client.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockInfluxClientMockRecorder) Write(bp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockInfluxClient)(nil).Write), bp)
}
